### ISSUE TITLE
Store the state of the conversation in a database

### ISSUE THREAD

**Issue by resinas** [isa-group/offline-directline#8]
At this moment, the state of the conversation is stored in memory. However, we could use a database for that. Redis, for instance, could be a good candidate for that. Maybe we could have both ways of working and use configuration to choose the one that should be used.

**Comment by maribelrb22** [comment]
62acc014dbadc3960b235f89f1bac1eeedacc1dd and 1d978d34eec589a934fadf1ff13de3b4ad56381e may close this
